---
- hosts: koding
  sudo: yes
  remote_user: ivaerospace
  tasks:
    - name: Mover script de actualización de proyecto
      shell: mv iv-aerospace/update.sh .
    - name: Actualizar proyecto
      script: update.sh
